project_name: supabase
before:
  hooks:
    - go mod tidy
builds:
  - id: supabase
    binary: supabase
    goos:
      - darwin
      - linux
      - windows
changelog:
  skip: true
brews:
  - tap:
      owner: soedirgo
      name: homebrew-tap
    commit_author:
      name: Bobbie Soedirgo
      email: bobbie@soedirgo.dev
    homepage: https://supabase.io
    description: Supabase CLI
    license: MIT
scoop:
  bucket:
    owner: soedirgo
    name: scoop-bucket
  commit_author:
    name: Bobbie Soedirgo
    email: bobbie@soedirgo.dev
  homepage: https://supabase.io
  description: Supabase CLI
  license: MIT
