project_name: supabase
before:
  hooks:
    - go mod tidy
builds:
  - id: supabase
    binary: supabase
    goos:
      - darwin
      - linux
      - windows
changelog:
  skip: true
brews:
  - tap:
      owner: soedirgo
      name: homebrew-tap
    description: Supabase CLI
    homepage: https://supabase.io
    license: MIT
scoop:
  bucket:
    owner: soedirgo
    name: scoop-bucket
  description: Supabase CLI
  homepage: https://supabase.io
  license: MIT
